# =============================================================================
# 16_report_generator.R
# Behavioural Segmentation Toolkit
#
# Purpose:
#   - Generate a complete client-ready segmentation report
#   - Consolidate modelling, validation, profiling, personas and interventions
#   - Produce HTML and Microsoft Word outputs from a generated R Markdown file
#
# Expected inputs:
#   outputs/tables/09_validated_model_candidates.csv
#   outputs/tables/10_candidate_profile_summary.csv
#   outputs/tables/11_segment_sizes.csv
#   outputs/tables/11_segment_difference_tests.csv
#   outputs/tables/11_segment_distinguishing_variables.csv
#   outputs/tables/12_segment_names.csv
#   outputs/final/13_segment_numeric_profiles.csv
#   outputs/final/13_segment_categorical_profiles.csv
#   outputs/final/14_persona_details.csv
#   outputs/final/personas/*.png
#   outputs/final/15_intervention_strategy.csv
#   outputs/final/15_intervention_actions.csv
#   outputs/final/15_message_framework.csv
#   outputs/final/15_channel_strategy.csv
#   outputs/final/15_kpi_framework.csv
#   outputs/final/15_implementation_priorities.csv
#
# Main outputs:
#   outputs/report/16_behavioural_segmentation_report.html
#   outputs/report/16_behavioural_segmentation_report.docx
#   outputs/report/16_behavioural_segmentation_report.Rmd
#   outputs/report/figures/*.png
#   outputs/logs/16_report_generator.log
#
# Notes:
#   - HTML and Word are generated by default.
#   - PDF generation is optional and requires a working LaTeX installation.
# =============================================================================


# =============================================================================
# 0. Environment
# =============================================================================

rm(list = ls())
gc()

options(
  stringsAsFactors = FALSE,
  warn = 1,
  scipen = 999
)


# =============================================================================
# 1. User settings
# =============================================================================

report_title <- "Behavioural Segmentation Report"
report_subtitle <- "Validated segments, personas and intervention recommendations"
report_author <- "Behavioural Segmentation Toolkit"

generate_html <- TRUE
generate_word <- TRUE
generate_pdf <- FALSE

include_persona_images <- TRUE
include_technical_appendix <- TRUE

top_validation_models <- 10
top_key_variables <- 20
top_numeric_variables_per_segment <- 8
top_categorical_rows_per_segment <- 12


# =============================================================================
# 2. Packages
# =============================================================================

required_packages <- c(
  "dplyr",
  "readr",
  "tidyr",
  "purrr",
  "tibble",
  "stringr",
  "ggplot2",
  "knitr",
  "rmarkdown"
)

missing_packages <- setdiff(
  required_packages,
  rownames(installed.packages())
)

if (length(missing_packages) > 0) {
  install.packages(
    missing_packages,
    dependencies = TRUE
  )
}

invisible(
  lapply(
    required_packages,
    library,
    character.only = TRUE
  )
)


# =============================================================================
# 3. Helper functions
# =============================================================================

find_project_root <- function(start_dir = getwd()) {

  current <- normalizePath(
    start_dir,
    winslash = "/",
    mustWork = TRUE
  )

  for (i in seq_len(12)) {

    if (
      dir.exists(file.path(current, "data")) &&
      dir.exists(file.path(current, "outputs"))
    ) {
      return(current)
    }

    parent <- dirname(current)

    if (identical(parent, current)) {
      break
    }

    current <- parent
  }

  stop("Project root not found.")
}


create_directory <- function(path) {

  if (!dir.exists(path)) {
    dir.create(
      path,
      recursive = TRUE,
      showWarnings = FALSE
    )
  }

  invisible(path)
}


safe_read_csv <- function(path) {

  if (!file.exists(path)) {
    return(tibble::tibble())
  }

  readr::read_csv(
    path,
    show_col_types = FALSE
  )
}


first_existing_file <- function(paths) {

  existing <- paths[
    file.exists(paths)
  ]

  if (length(existing) == 0) {
    return(NA_character_)
  }

  existing[1]
}


read_first_existing_csv <- function(paths) {

  selected <- first_existing_file(paths)

  if (is.na(selected)) {
    return(tibble::tibble())
  }

  safe_read_csv(selected)
}


safe_text <- function(x, default = "Not available") {

  x <- as.character(x)

  x <- x[
    !is.na(x) &
      stringr::str_trim(x) != ""
  ]

  if (length(x) == 0) {
    return(default)
  }

  x[1]
}


safe_numeric <- function(x, default = NA_real_) {

  value <- suppressWarnings(
    as.numeric(x)
  )

  if (length(value) == 0 || is.na(value[1])) {
    return(default)
  }

  value[1]
}


format_percent <- function(x, digits = 1) {

  x <- suppressWarnings(
    as.numeric(x)
  )

  ifelse(
    is.na(x),
    "",
    paste0(
      formatC(
        x,
        format = "f",
        digits = digits
      ),
      "%"
    )
  )
}


escape_r_string <- function(x) {

  x |>
    stringr::str_replace_all("\\\\", "\\\\\\\\") |>
    stringr::str_replace_all('"', '\\\\"')
}


relative_path <- function(path, start) {

  path <- normalizePath(
    path,
    winslash = "/",
    mustWork = FALSE
  )

  start <- normalizePath(
    start,
    winslash = "/",
    mustWork = FALSE
  )

  prefix <- paste0(
    start,
    "/"
  )

  if (startsWith(path, prefix)) {
    return(
      substring(
        path,
        nchar(prefix) + 1
      )
    )
  }

  path
}


clean_names_for_display <- function(data) {

  if (nrow(data) == 0) {
    return(data)
  }

  names(data) <- names(data) |>
    stringr::str_replace_all("_", " ") |>
    stringr::str_to_title()

  data
}


write_log <- function(..., file) {

  message_text <- paste0(...)

  cat(
    format(
      Sys.time(),
      "%Y-%m-%d %H:%M:%S"
    ),
    " | ",
    message_text,
    "\n",
    file = file,
    append = TRUE,
    sep = ""
  )
}


# =============================================================================
# 4. Paths
# =============================================================================

project_dir <- find_project_root()

tables_dir <- file.path(
  project_dir,
  "outputs",
  "tables"
)

final_dir <- file.path(
  project_dir,
  "outputs",
  "final"
)

report_dir <- file.path(
  project_dir,
  "outputs",
  "report"
)

report_figures_dir <- file.path(
  report_dir,
  "figures"
)

logs_dir <- file.path(
  project_dir,
  "outputs",
  "logs"
)

personas_dir <- file.path(
  final_dir,
  "personas"
)

invisible(
  lapply(
    c(
      report_dir,
      report_figures_dir,
      logs_dir
    ),
    create_directory
  )
)

log_file <- file.path(
  logs_dir,
  "16_report_generator.log"
)

if (file.exists(log_file)) {
  file.remove(log_file)
}

write_log(
  "Report generation started.",
  file = log_file
)


# =============================================================================
# 5. Load source tables
# =============================================================================

validated_models <- read_first_existing_csv(
  c(
    file.path(
      tables_dir,
      "09_validated_model_candidates.csv"
    ),
    file.path(
      final_dir,
      "09_validated_model_candidates.csv"
    )
  )
)

candidate_profiles <- read_first_existing_csv(
  c(
    file.path(
      tables_dir,
      "10_candidate_profile_summary.csv"
    ),
    file.path(
      final_dir,
      "10_candidate_profile_summary.csv"
    )
  )
)

segment_sizes <- read_first_existing_csv(
  c(
    final_dir |> file.path("13_segment_sizes.csv"),
    tables_dir |> file.path("11_segment_sizes.csv")
  )
)

difference_tests <- read_first_existing_csv(
  c(
    tables_dir |> file.path("11_segment_difference_tests.csv"),
    final_dir |> file.path("11_segment_difference_tests.csv")
  )
)

key_variables <- read_first_existing_csv(
  c(
    final_dir |> file.path("13_segment_key_variables.csv"),
    tables_dir |> file.path("11_segment_distinguishing_variables.csv")
  )
)

segment_names <- read_first_existing_csv(
  c(
    tables_dir |> file.path("12_segment_names.csv"),
    final_dir |> file.path("12_segment_names.csv")
  )
)

numeric_profiles <- safe_read_csv(
  file.path(
    final_dir,
    "13_segment_numeric_profiles.csv"
  )
)

categorical_profiles <- safe_read_csv(
  file.path(
    final_dir,
    "13_segment_categorical_profiles.csv"
  )
)

persona_details <- safe_read_csv(
  file.path(
    final_dir,
    "14_persona_details.csv"
  )
)

intervention_strategy <- safe_read_csv(
  file.path(
    final_dir,
    "15_intervention_strategy.csv"
  )
)

intervention_actions <- safe_read_csv(
  file.path(
    final_dir,
    "15_intervention_actions.csv"
  )
)

message_framework <- safe_read_csv(
  file.path(
    final_dir,
    "15_message_framework.csv"
  )
)

channel_strategy <- safe_read_csv(
  file.path(
    final_dir,
    "15_channel_strategy.csv"
  )
)

kpi_framework <- safe_read_csv(
  file.path(
    final_dir,
    "15_kpi_framework.csv"
  )
)

implementation_priorities <- safe_read_csv(
  file.path(
    final_dir,
    "15_implementation_priorities.csv"
  )
)


# =============================================================================
# 6. Input validation
# =============================================================================

required_inputs <- list(
  segment_sizes = segment_sizes,
  persona_details = persona_details,
  intervention_strategy =
    intervention_strategy,
  intervention_actions =
    intervention_actions,
  message_framework =
    message_framework,
  kpi_framework =
    kpi_framework
)

missing_required <- names(required_inputs)[
  vapply(
    required_inputs,
    nrow,
    integer(1)
  ) == 0
]

if (length(missing_required) > 0) {

  stop(
    "The following required inputs are missing or empty: ",
    paste(
      missing_required,
      collapse = ", "
    ),
    ". Run Stages 13–15 before Stage 16."
  )
}

write_log(
  "Required source tables loaded successfully.",
  file = log_file
)


# =============================================================================
# 7. Standardise key fields
# =============================================================================

if (!"working_name" %in% names(segment_sizes)) {

  if (
    "segment" %in% names(segment_sizes) &&
    nrow(segment_names) > 0 &&
    all(
      c(
        "segment",
        "working_name"
      ) %in% names(segment_names)
    )
  ) {

    segment_sizes <- segment_sizes |>
      dplyr::left_join(
        segment_names |>
          dplyr::select(
            segment,
            working_name
          ) |>
          dplyr::distinct(),
        by = "segment"
      )
  }
}

if (!"share_pct" %in% names(segment_sizes)) {

  possible_share_columns <- intersect(
    c(
      "segment_share_pct",
      "percentage",
      "share",
      "pct"
    ),
    names(segment_sizes)
  )

  if (length(possible_share_columns) > 0) {

    segment_sizes <- segment_sizes |>
      dplyr::mutate(
        share_pct =
          .data[[
            possible_share_columns[1]
          ]]
      )
  }
}

if (!"n" %in% names(segment_sizes)) {

  possible_n_columns <- intersect(
    c(
      "segment_n",
      "count",
      "frequency"
    ),
    names(segment_sizes)
  )

  if (length(possible_n_columns) > 0) {

    segment_sizes <- segment_sizes |>
      dplyr::mutate(
        n =
          .data[[
            possible_n_columns[1]
          ]]
      )
  }
}


# =============================================================================
# 8. Create report figures
# =============================================================================

segment_size_figure <- file.path(
  report_figures_dir,
  "16_segment_sizes.png"
)

segment_size_plot_data <- segment_sizes |>
  dplyr::mutate(
    working_name =
      dplyr::coalesce(
        working_name,
        as.character(segment)
      ),
    share_pct =
      suppressWarnings(
        as.numeric(share_pct)
      )
  ) |>
  dplyr::arrange(share_pct) |>
  dplyr::mutate(
    working_name =
      factor(
        working_name,
        levels = working_name
      )
  )

segment_size_plot <- ggplot2::ggplot(
  segment_size_plot_data,
  ggplot2::aes(
    x = working_name,
    y = share_pct
  )
) +
  ggplot2::geom_col(
    width = 0.7
  ) +
  ggplot2::geom_text(
    ggplot2::aes(
      label =
        paste0(
          round(
            share_pct,
            1
          ),
          "%"
        )
    ),
    hjust = -0.15,
    size = 4
  ) +
  ggplot2::coord_flip() +
  ggplot2::labs(
    title = "Final segment distribution",
    x = NULL,
    y = "Share of sample (%)"
  ) +
  ggplot2::theme_minimal(
    base_size = 12
  ) +
  ggplot2::expand_limits(
    y =
      max(
        segment_size_plot_data$share_pct,
        na.rm = TRUE
      ) *
        1.15
  )

ggplot2::ggsave(
  filename = segment_size_figure,
  plot = segment_size_plot,
  width = 9,
  height = 5.5,
  dpi = 180
)


priority_figure <- file.path(
  report_figures_dir,
  "16_implementation_priorities.png"
)

if (
  nrow(implementation_priorities) > 0 &&
  all(
    c(
      "working_name",
      "priority_score"
    ) %in%
      names(
        implementation_priorities
      )
  )
) {

  priority_plot_data <- implementation_priorities |>
    dplyr::mutate(
      priority_score =
        suppressWarnings(
          as.numeric(priority_score)
        )
    ) |>
    dplyr::arrange(priority_score) |>
    dplyr::mutate(
      working_name =
        factor(
          working_name,
          levels = working_name
        )
    )

  priority_plot <- ggplot2::ggplot(
    priority_plot_data,
    ggplot2::aes(
      x = working_name,
      y = priority_score
    )
  ) +
    ggplot2::geom_col(
      width = 0.65
    ) +
    ggplot2::geom_text(
      ggplot2::aes(
        label =
          implementation_priority
      ),
      hjust = -0.12,
      size = 4
    ) +
    ggplot2::coord_flip() +
    ggplot2::scale_y_continuous(
      breaks = 1:4,
      limits = c(
        0,
        4.8
      )
    ) +
    ggplot2::labs(
      title = "Implementation priority by segment",
      x = NULL,
      y = "Priority score"
    ) +
    ggplot2::theme_minimal(
      base_size = 12
    )

  ggplot2::ggsave(
    filename = priority_figure,
    plot = priority_plot,
    width = 9,
    height = 5.5,
    dpi = 180
  )

} else {

  priority_figure <- NA_character_
}


# =============================================================================
# 9. Identify final model and headline statistics
# =============================================================================

final_model <- "Not available"
validation_score <- NA_real_
mean_jaccard <- NA_real_
number_of_segments <- nrow(segment_sizes)
total_sample <- sum(
  suppressWarnings(
    as.numeric(
      segment_sizes$n
    )
  ),
  na.rm = TRUE
)

if (nrow(validated_models) > 0) {

  model_column <- intersect(
    c(
      "model_id",
      "candidate_id",
      "model_name",
      "model"
    ),
    names(validated_models)
  )

  score_column <- intersect(
    c(
      "validation_score",
      "overall_validation_score",
      "score"
    ),
    names(validated_models)
  )

  jaccard_column <- intersect(
    c(
      "mean_jaccard",
      "bootstrap_mean_jaccard",
      "jaccard_mean"
    ),
    names(validated_models)
  )

  if (length(score_column) > 0) {

    best_index <- which.max(
      suppressWarnings(
        as.numeric(
          validated_models[[
            score_column[1]
          ]]
        )
      )
    )

  } else {

    best_index <- 1
  }

  if (length(model_column) > 0) {
    final_model <- safe_text(
      validated_models[[
        model_column[1]
      ]][best_index]
    )
  }

  if (length(score_column) > 0) {
    validation_score <- safe_numeric(
      validated_models[[
        score_column[1]
      ]][best_index]
    )
  }

  if (length(jaccard_column) > 0) {
    mean_jaccard <- safe_numeric(
      validated_models[[
        jaccard_column[1]
      ]][best_index]
    )
  }
}


# =============================================================================
# 10. Prepare persona image map
# =============================================================================

persona_image_map <- tibble::tibble()

if (
  include_persona_images &&
  dir.exists(personas_dir)
) {

  persona_images <- list.files(
    personas_dir,
    pattern = "^14_persona_.*\\.png$",
    full.names = TRUE
  )

  if (length(persona_images) > 0) {

    persona_image_map <- tibble::tibble(
      image_path = persona_images,
      image_key =
        basename(persona_images) |>
        stringr::str_remove(
          "^14_persona_"
        ) |>
        stringr::str_remove(
          "\\.png$"
        )
    )
  }
}


# =============================================================================
# 11. Save report data object
# =============================================================================

report_data <- list(
  report_title = report_title,
  report_subtitle = report_subtitle,
  report_author = report_author,
  final_model = final_model,
  validation_score = validation_score,
  mean_jaccard = mean_jaccard,
  number_of_segments = number_of_segments,
  total_sample = total_sample,
  segment_sizes = segment_sizes,
  validated_models = validated_models,
  candidate_profiles = candidate_profiles,
  difference_tests = difference_tests,
  key_variables = key_variables,
  numeric_profiles = numeric_profiles,
  categorical_profiles =
    categorical_profiles,
  persona_details = persona_details,
  intervention_strategy =
    intervention_strategy,
  intervention_actions =
    intervention_actions,
  message_framework =
    message_framework,
  channel_strategy =
    channel_strategy,
  kpi_framework = kpi_framework,
  implementation_priorities =
    implementation_priorities,
  segment_size_figure =
    segment_size_figure,
  priority_figure =
    priority_figure,
  persona_image_map =
    persona_image_map,
  include_persona_images =
    include_persona_images,
  include_technical_appendix =
    include_technical_appendix,
  top_validation_models =
    top_validation_models,
  top_key_variables =
    top_key_variables,
  top_numeric_variables_per_segment =
    top_numeric_variables_per_segment,
  top_categorical_rows_per_segment =
    top_categorical_rows_per_segment
)

report_data_file <- file.path(
  report_dir,
  "16_report_data.rds"
)

saveRDS(
  report_data,
  report_data_file
)


# =============================================================================
# 12. Generate R Markdown document
# =============================================================================

rmd_file <- file.path(
  report_dir,
  "16_behavioural_segmentation_report.Rmd"
)

rmd_lines <- c(
  "---",
  paste0(
    'title: "',
    escape_r_string(report_title),
    '"'
  ),
  paste0(
    'subtitle: "',
    escape_r_string(report_subtitle),
    '"'
  ),
  paste0(
    'author: "',
    escape_r_string(report_author),
    '"'
  ),
  'date: "`r format(Sys.Date(), \'%d %B %Y\')`"',
  "output:",
  "  html_document:",
  "    toc: true",
  "    toc_depth: 3",
  "    number_sections: true",
  "    theme: flatly",
  "    df_print: paged",
  "  word_document:",
  "    toc: true",
  "    toc_depth: 3",
  "    number_sections: true",
  "  pdf_document:",
  "    toc: true",
  "    toc_depth: 3",
  "    number_sections: true",
  "geometry: margin=1in",
  "---",
  "",
  "```{r setup, include=FALSE}",
  "knitr::opts_chunk$set(",
  "  echo = FALSE,",
  "  warning = FALSE,",
  "  message = FALSE,",
  "  fig.align = 'center',",
  "  out.width = '95%'",
  ")",
  "",
  "library(dplyr)",
  "library(tidyr)",
  "library(stringr)",
  "library(knitr)",
  "",
  paste0(
    'report_data <- readRDS("',
    escape_r_string(
      relative_path(
        report_data_file,
        report_dir
      )
    ),
    '")'
  ),
  "",
  "segment_sizes <- report_data$segment_sizes",
  "validated_models <- report_data$validated_models",
  "candidate_profiles <- report_data$candidate_profiles",
  "difference_tests <- report_data$difference_tests",
  "key_variables <- report_data$key_variables",
  "numeric_profiles <- report_data$numeric_profiles",
  "categorical_profiles <- report_data$categorical_profiles",
  "persona_details <- report_data$persona_details",
  "intervention_strategy <- report_data$intervention_strategy",
  "intervention_actions <- report_data$intervention_actions",
  "message_framework <- report_data$message_framework",
  "channel_strategy <- report_data$channel_strategy",
  "kpi_framework <- report_data$kpi_framework",
  "implementation_priorities <- report_data$implementation_priorities",
  "",
  "display_table <- function(data, caption = NULL, digits = 2) {",
  "  if (nrow(data) == 0) {",
  "    cat('*No data available.*')",
  "    return(invisible(NULL))",
  "  }",
  "",
  "  display_data <- data",
  "",
  "  numeric_columns <- vapply(",
  "    display_data,",
  "    is.numeric,",
  "    logical(1)",
  "  )",
  "",
  "  display_data[numeric_columns] <- lapply(",
  "    display_data[numeric_columns],",
  "    round,",
  "    digits = digits",
  "  )",
  "",
  "  names(display_data) <- names(display_data) |>",
  "    str_replace_all('_', ' ') |>",
  "    str_to_title()",
  "",
  "  print(",
  "    knitr::kable(",
  "      display_data,",
  "      caption = caption,",
  "      row.names = FALSE",
  "    )",
  "  )",
  "}",
  "",
  "normalise_key <- function(x) {",
  "  x |>",
  "    str_to_lower() |>",
  "    str_replace_all('[^a-z0-9]+', '_') |>",
  "    str_replace_all('^_|_$', '')",
  "}",
  "```",
  "",
  "# Executive summary",
  "",
  "The final segmentation contains **`r report_data$number_of_segments` segments** based on a sample of **`r format(report_data$total_sample, big.mark = ',')` respondents**.",
  "",
  "The selected solution was **`r report_data$final_model`**.",
  "",
  "```{r headline-validation, results='asis'}",
  "if (!is.na(report_data$validation_score)) {",
  "  cat(",
  "    paste0(",
  "      'The final model achieved a validation score of **',",
  "      round(report_data$validation_score, 3),",
  "      '**.'",
  "    )",
  "  )",
  "}",
  "",
  "if (!is.na(report_data$mean_jaccard)) {",
  "  cat(",
  "    paste0(",
  "      ' Mean bootstrap Jaccard stability was **',",
  "      round(report_data$mean_jaccard, 3),",
  "      '**.'",
  "    )",
  "  )",
  "}",
  "```",
  "",
  "The segmentation is designed to support differentiated communication, service design and intervention planning. The segment profiles should be interpreted as group-level tendencies rather than deterministic descriptions of every individual.",
  "",
  "```{r segment-size-figure, out.width='90%'}",
  "knitr::include_graphics(",
  "  report_data$segment_size_figure",
  ")",
  "```",
  "",
  "```{r executive-priority-table, results='asis'}",
  "if (nrow(implementation_priorities) > 0) {",
  "  display_table(",
  "    implementation_priorities |>",
  "      select(",
  "        overall_rank,",
  "        working_name,",
  "        share_pct,",
  "        implementation_priority,",
  "        recommended_sequence",
  "      ),",
  "    caption = 'Recommended implementation sequence'",
  "  )",
  "}",
  "```",
  "",
  "# Methodology",
  "",
  "## Analytical workflow",
  "",
  "The toolkit applies a structured workflow covering data audit, preprocessing, feature screening, candidate feature-set construction, distance comparison, model comparison, validation, final model selection, segment profiling, naming, persona generation and intervention planning.",
  "",
  "The model-selection process combines statistical quality, stability, segment-size balance and practical interpretability. Internal indices are used as diagnostics rather than as the sole basis for choosing the final solution.",
  "",
  "## Validation framework",
  "",
  "Candidate models are assessed using repeated or bootstrap-based stability diagnostics, cluster separation, minimum segment size and profile distinctness. The final solution is selected only after reviewing both statistical diagnostics and the substantive profile differences between segments.",
  "",
  "```{r validation-table, results='asis'}",
  "if (nrow(validated_models) > 0) {",
  "  display_table(",
  "    validated_models |>",
  "      slice_head(n = report_data$top_validation_models),",
  "    caption = 'Leading validated model candidates'",
  "  )",
  "}",
  "```",
  "",
  "# Final segment solution",
  "",
  "## Segment sizes",
  "",
  "```{r segment-size-table, results='asis'}",
  "display_table(",
  "  segment_sizes,",
  "  caption = 'Final segment sizes'",
  ")",
  "```",
  "",
  "## Segment overview",
  "",
  "```{r persona-overview, results='asis'}",
  "for (i in seq_len(nrow(persona_details))) {",
  "",
  "  row <- persona_details[i, , drop = FALSE]",
  "",
  "  cat(",
  "    paste0(",
  "      '\\n### ',",
  "      row$working_name,",
  "      '\\n\\n'",
  "    )",
  "  )",
  "",
  "  cat(",
  "    paste0(",
  "      '**Segment size:** ',",
  "      row$n,",
  "      ' respondents (',",
  "      round(row$share_pct, 1),",
  "      '%)\\n\\n'",
  "    )",
  "  )",
  "",
  "  cat(",
  "    paste0(",
  "      '> ',",
  "      row$persona_quote,",
  "      '\\n\\n'",
  "    )",
  "  )",
  "",
  "  cat(",
  "    paste0(",
  "      row$short_narrative,",
  "      '\\n\\n'",
  "    )",
  "  )",
  "",
  "  cat(",
  "    paste0(",
  "      '**Key characteristics:** ',",
  "      row$key_characteristics,",
  "      '\\n\\n'",
  "    )",
  "  )",
  "",
  "  cat(",
  "    paste0(",
  "      '**Profiling signals:** ',",
  "      row$profiling_signals,",
  "      '\\n\\n'",
  "    )",
  "  )",
  "",
  "  if (report_data$include_persona_images &&",
  "      nrow(report_data$persona_image_map) > 0) {",
  "",
  "    persona_key <- normalise_key(row$working_name)",
  "",
  "    image_match <- report_data$persona_image_map |>",
  "      filter(image_key == persona_key)",
  "",
  "    if (nrow(image_match) > 0) {",
  "      print(",
  "        knitr::include_graphics(",
  "          image_match$image_path[1]",
  "        )",
  "      )",
  "      cat('\\n\\n')",
  "    }",
  "  }",
  "}",
  "```",
  "",
  "# Segment profiles",
  "",
  "```{r detailed-profiles, results='asis'}",
  "segments <- unique(persona_details$segment)",
  "",
  "for (segment_value in segments) {",
  "",
  "  segment_persona <- persona_details |>",
  "    filter(segment == segment_value) |>",
  "    slice_head(n = 1)",
  "",
  "  segment_name <- segment_persona$working_name",
  "",
  "  cat(",
  "    paste0(",
  "      '\\n## ',",
  "      segment_name,",
  "      '\\n\\n'",
  "    )",
  "  )",
  "",
  "  if (nrow(numeric_profiles) > 0 &&",
  "      'segment' %in% names(numeric_profiles)) {",
  "",
  "    numeric_segment <- numeric_profiles |>",
  "      filter(segment == segment_value)",
  "",
  "    if ('standardised_mean' %in% names(numeric_segment)) {",
  "      numeric_segment <- numeric_segment |>",
  "        arrange(desc(abs(standardised_mean)))",
  "    }",
  "",
  "    numeric_segment <- numeric_segment |>",
  "      slice_head(",
  "        n = report_data$top_numeric_variables_per_segment",
  "      )",
  "",
  "    cat('\\n### Numeric profile\\n\\n')",
  "    display_table(numeric_segment)",
  "    cat('\\n\\n')",
  "  }",
  "",
  "  if (nrow(categorical_profiles) > 0 &&",
  "      'segment' %in% names(categorical_profiles)) {",
  "",
  "    categorical_segment <- categorical_profiles |>",
  "      filter(segment == segment_value)",
  "",
  "    if ('within_segment_share' %in% names(categorical_segment)) {",
  "      categorical_segment <- categorical_segment |>",
  "        arrange(desc(within_segment_share))",
  "    }",
  "",
  "    categorical_segment <- categorical_segment |>",
  "      slice_head(",
  "        n = report_data$top_categorical_rows_per_segment",
  "      )",
  "",
  "    cat('\\n### Categorical profile\\n\\n')",
  "    display_table(categorical_segment)",
  "    cat('\\n\\n')",
  "  }",
  "}",
  "```",
  "",
  "# Intervention strategy",
  "",
  "The recommendations below translate the observed segment characteristics into practical communication and service-design principles. They should be tested in implementation and refined with subject-matter experts.",
  "",
  "```{r intervention-strategy, results='asis'}",
  "for (i in seq_len(nrow(intervention_strategy))) {",
  "",
  "  row <- intervention_strategy[i, , drop = FALSE]",
  "",
  "  cat(",
  "    paste0(",
  "      '\\n## ',",
  "      row$working_name,",
  "      '\\n\\n'",
  "    )",
  "  )",
  "",
  "  strategy_table <- tibble::tibble(",
  "    Component = c(",
  "      'Core behavioural problem',",
  "      'Strategic objective',",
  "      'Behavioural strategy',",
  "      'Service strategy',",
  "      'Channel strategy',",
  "      'Support intensity',",
  "      'Delivery style',",
  "      'Implementation priority'",
  "    ),",
  "    Recommendation = c(",
  "      row$core_behavioural_problem,",
  "      row$strategic_objective,",
  "      row$behavioural_strategy,",
  "      row$service_strategy,",
  "      row$channel_strategy,",
  "      row$suggested_support_intensity,",
  "      row$suggested_delivery_style,",
  "      row$implementation_priority",
  "    )",
  "  )",
  "",
  "  display_table(strategy_table)",
  "  cat('\\n\\n')",
  "",
  "  segment_actions <- intervention_actions |>",
  "    filter(segment == row$segment) |>",
  "    select(",
  "      action_rank,",
  "      action_category,",
  "      recommended_action,",
  "      delivery_mode,",
  "      implementation_horizon",
  "    )",
  "",
  "  cat('\\n### Recommended actions\\n\\n')",
  "  display_table(segment_actions)",
  "  cat('\\n\\n')",
  "}",
  "```",
  "",
  "# Messaging framework",
  "",
  "```{r message-framework, results='asis'}",
  "for (i in seq_len(nrow(message_framework))) {",
  "",
  "  row <- message_framework[i, , drop = FALSE]",
  "",
  "  cat(",
  "    paste0(",
  "      '\\n## ',",
  "      row$working_name,",
  "      '\\n\\n'",
  "    )",
  "  )",
  "",
  "  message_table <- tibble::tibble(",
  "    Component = c(",
  "      'Primary message',",
  "      'Secondary message',",
  "      'Proof point',",
  "      'Call to action',",
  "      'Tone',",
  "      'Avoid'",
  "    ),",
  "    Guidance = c(",
  "      row$primary_message,",
  "      row$secondary_message,",
  "      row$proof_point,",
  "      row$call_to_action,",
  "      row$tone,",
  "      row$avoid",
  "    )",
  "  )",
  "",
  "  display_table(message_table)",
  "  cat('\\n\\n')",
  "}",
  "```",
  "",
  "# Channel and service strategy",
  "",
  "```{r channel-strategy-table, results='asis'}",
  "display_table(",
  "  channel_strategy,",
  "  caption = 'Channel and service-delivery recommendations'",
  ")",
  "```",
  "",
  "# Measurement framework",
  "",
  "The KPI framework distinguishes immediate engagement and conversion outcomes from confidence, access, retention and behavioural progression measures.",
  "",
  "```{r kpi-framework, results='asis'}",
  "for (segment_value in unique(kpi_framework$segment)) {",
  "",
  "  segment_name <- kpi_framework |>",
  "    filter(segment == segment_value) |>",
  "    pull(working_name) |>",
  "    unique() |>",
  "    head(1)",
  "",
  "  cat(",
  "    paste0(",
  "      '\\n## ',",
  "      segment_name,",
  "      '\\n\\n'",
  "    )",
  "  )",
  "",
  "  display_table(",
  "    kpi_framework |>",
  "      filter(segment == segment_value) |>",
  "      select(",
  "        kpi_rank,",
  "        kpi_category,",
  "        kpi_name,",
  "        definition,",
  "        expected_direction",
  "      )",
  "  )",
  "",
  "  cat('\\n\\n')",
  "}",
  "```",
  "",
  "# Implementation priorities",
  "",
  "```{r implementation-priority-figure, out.width='90%'}",
  "if (!is.na(report_data$priority_figure)) {",
  "  knitr::include_graphics(",
  "    report_data$priority_figure",
  "  )",
  "}",
  "```",
  "",
  "```{r implementation-priority-table, results='asis'}",
  "display_table(",
  "  implementation_priorities,",
  "  caption = 'Implementation priority and recommended sequence'",
  ")",
  "```",
  "",
  "# Interpretation and use",
  "",
  "The segments are intended to support differentiated decisions rather than to label individuals permanently. Assignment uncertainty, changes in circumstances and differences within each segment should be considered when using the results.",
  "",
  "Recommended practical uses include campaign targeting, service pathway design, message testing, resource prioritisation and the development of a short segment-assignment questionnaire. Intervention recommendations should be piloted and evaluated before large-scale implementation.",
  "",
  "```{r technical-appendix, results='asis'}",
  "if (report_data$include_technical_appendix) {",
  "",
  "  cat('\\n# Technical appendix\\n\\n')",
  "",
  "  if (nrow(candidate_profiles) > 0) {",
  "    cat('\\n## Candidate profile comparison\\n\\n')",
  "    display_table(candidate_profiles)",
  "    cat('\\n\\n')",
  "  }",
  "",
  "  if (nrow(key_variables) > 0) {",
  "    cat('\\n## Key distinguishing variables\\n\\n')",
  "    display_table(",
  "      key_variables |>",
  "        slice_head(n = report_data$top_key_variables)",
  "    )",
  "    cat('\\n\\n')",
  "  }",
  "",
  "  if (nrow(difference_tests) > 0) {",
  "    cat('\\n## Statistical difference tests\\n\\n')",
  "    display_table(difference_tests)",
  "    cat('\\n\\n')",
  "  }",
  "",
  "  cat('\\n## Reproducibility information\\n\\n')",
  "  cat(",
  "    paste0(",
  "      'Report generated on ',",
  "      format(Sys.time(), '%Y-%m-%d %H:%M:%S'),",
  "      '.\\n\\n'",
  "    )",
  "  )",
  "",
  "  session_text <- capture.output(sessionInfo())",
  "  cat('```text\\n')",
  "  cat(paste(session_text, collapse = '\\n'))",
  "  cat('\\n```\\n')",
  "}",
  "```"
)

writeLines(
  rmd_lines,
  con = rmd_file,
  useBytes = TRUE
)

write_log(
  "R Markdown source generated.",
  file = log_file
)


# =============================================================================
# 13. Render report outputs
# =============================================================================

render_report <- function(
    output_format,
    output_file
) {

  write_log(
    "Rendering ",
    output_file,
    ".",
    file = log_file
  )

  tryCatch(
    {

      rmarkdown::render(
        input = rmd_file,
        output_format = output_format,
        output_file = output_file,
        output_dir = report_dir,
        knit_root_dir = report_dir,
        envir = new.env(
          parent = globalenv()
        ),
        quiet = TRUE
      )

      write_log(
        "Successfully rendered ",
        output_file,
        ".",
        file = log_file
      )

      TRUE
    },
    error = function(error) {

      write_log(
        "Failed to render ",
        output_file,
        ": ",
        conditionMessage(error),
        file = log_file
      )

      warning(
        "Could not render ",
        output_file,
        ": ",
        conditionMessage(error)
      )

      FALSE
    }
  )
}


render_results <- list()

if (generate_html) {

  render_results$html <- render_report(
    output_format =
      rmarkdown::html_document(
        toc = TRUE,
        toc_depth = 3,
        number_sections = TRUE,
        theme = "flatly",
        df_print = "paged"
      ),
    output_file =
      "16_behavioural_segmentation_report.html"
  )
}

if (generate_word) {

  render_results$word <- render_report(
    output_format =
      rmarkdown::word_document(
        toc = TRUE,
        toc_depth = 3,
        number_sections = TRUE
      ),
    output_file =
      "16_behavioural_segmentation_report.docx"
  )
}

if (generate_pdf) {

  if (!rmarkdown::pandoc_available()) {

    warning(
      "Pandoc is unavailable. PDF report was not generated."
    )

    render_results$pdf <- FALSE

  } else {

    render_results$pdf <- render_report(
      output_format =
        rmarkdown::pdf_document(
          toc = TRUE,
          toc_depth = 3,
          number_sections = TRUE
        ),
      output_file =
        "16_behavioural_segmentation_report.pdf"
    )
  }
}


# =============================================================================
# 14. Save session information
# =============================================================================

capture.output(
  sessionInfo(),
  file = file.path(
    logs_dir,
    "16_sessionInfo.txt"
  )
)


# =============================================================================
# 15. Final console summary
# =============================================================================

successful_outputs <- names(
  render_results
)[
  unlist(
    render_results
  )
]

failed_outputs <- names(
  render_results
)[
  !unlist(
    render_results
  )
]

cat(
  "\n",
  paste(rep("=", 78), collapse = ""),
  "\n",
  "BEHAVIOURAL SEGMENTATION TOOLKIT — REPORT GENERATION COMPLETE\n",
  paste(rep("=", 78), collapse = ""),
  "\n",
  "Segments included:              ",
  number_of_segments,
  "\n",
  "Total sample represented:       ",
  total_sample,
  "\n",
  "Final model:                    ",
  final_model,
  "\n",
  "Report source:\n",
  rmd_file,
  "\n",
  "Report directory:\n",
  report_dir,
  "\n",
  "Successfully generated:         ",
  ifelse(
    length(successful_outputs) == 0,
    "None",
    paste(
      successful_outputs,
      collapse = ", "
    )
  ),
  "\n",
  "Failed outputs:                 ",
  ifelse(
    length(failed_outputs) == 0,
    "None",
    paste(
      failed_outputs,
      collapse = ", "
    )
  ),
  "\n",
  paste(rep("=", 78), collapse = ""),
  "\n",
  sep = ""
)
