# =============================================================================
# 18_run_complete_pipeline.R
# Behavioural Segmentation Toolkit
#
# Purpose:
#   - Run the complete Behavioural Segmentation Toolkit from Stage 01 to Stage 17
#   - Validate that all required scripts exist
#   - Record execution time and status for every stage
#   - Stop safely when a required stage fails
#   - Produce a complete pipeline log and machine-readable execution summary
#
# Main usage:
#
#   source("18_run_complete_pipeline.R")
#
# Main outputs:
#
#   outputs/logs/18_complete_pipeline.log
#   outputs/logs/18_pipeline_execution_summary.csv
#   outputs/logs/18_pipeline_execution_summary.rds
#   outputs/logs/18_sessionInfo.txt
#
# Notes:
#   - By default, all stages 01–17 are run.
#   - Optional or unavailable scripts can be marked as non-required below.
#   - Set resume_from_stage to restart from a selected stage.
#   - Set continue_on_error = TRUE only for diagnostic use.
# =============================================================================


# =============================================================================
# 0. Environment
# =============================================================================

rm(list = ls())
gc()

options(
  stringsAsFactors = FALSE,
  warn = 1,
  scipen = 999
)


# =============================================================================
# 1. Pipeline settings
# =============================================================================

# First stage to run. Use NULL to start from Stage 01.
#
# Examples:
#   resume_from_stage <- NULL
#   resume_from_stage <- 9
#   resume_from_stage <- 16

resume_from_stage <- NULL


# Last stage to run. Use NULL to run through Stage 17.
#
# Examples:
#   stop_after_stage <- NULL
#   stop_after_stage <- 15

stop_after_stage <- NULL


# When FALSE, the pipeline stops immediately after a required stage fails.
# When TRUE, remaining stages are attempted.
#
# TRUE is mainly useful for diagnostics.

continue_on_error <- FALSE


# When TRUE, previously generated outputs are not used to skip stages.
# The selected stage range is always rerun.

force_rerun <- TRUE


# When TRUE, the console displays the output generated by each stage.

show_stage_output <- TRUE


# When TRUE, warnings are recorded but do not mark a stage as failed.

warnings_are_errors <- FALSE


# Delete an existing Stage 18 log before execution.

overwrite_log <- TRUE


# =============================================================================
# 2. Helper functions
# =============================================================================

find_project_root <- function(start_dir = getwd()) {

  current <- normalizePath(
    start_dir,
    winslash = "/",
    mustWork = TRUE
  )

  for (i in seq_len(15)) {

    has_outputs <- dir.exists(
      file.path(
        current,
        "outputs"
      )
    )

    has_data <- dir.exists(
      file.path(
        current,
        "data"
      )
    )

    has_r_scripts <- length(
      list.files(
        current,
        pattern = "^[0-9]{2}_.*\\.R$",
        full.names = FALSE
      )
    ) > 0

    if (
      has_outputs &&
      (has_data || has_r_scripts)
    ) {
      return(current)
    }

    parent <- dirname(current)

    if (identical(parent, current)) {
      break
    }

    current <- parent
  }

  stop(
    "Project root could not be identified. ",
    "Run this script from inside the Behavioural Segmentation Toolkit project."
  )
}


create_directory <- function(path) {

  if (!dir.exists(path)) {
    dir.create(
      path,
      recursive = TRUE,
      showWarnings = FALSE
    )
  }

  invisible(path)
}


timestamp <- function() {

  format(
    Sys.time(),
    "%Y-%m-%d %H:%M:%S"
  )
}


format_duration <- function(seconds) {

  if (is.na(seconds)) {
    return(NA_character_)
  }

  if (seconds < 60) {
    return(
      paste0(
        round(seconds, 2),
        " sec"
      )
    )
  }

  if (seconds < 3600) {

    minutes <- floor(
      seconds / 60
    )

    remaining_seconds <- round(
      seconds - minutes * 60,
      1
    )

    return(
      paste0(
        minutes,
        " min ",
        remaining_seconds,
        " sec"
      )
    )
  }

  hours <- floor(
    seconds / 3600
  )

  minutes <- floor(
    (
      seconds -
        hours * 3600
    ) / 60
  )

  remaining_seconds <- round(
    seconds -
      hours * 3600 -
      minutes * 60,
    1
  )

  paste0(
    hours,
    " h ",
    minutes,
    " min ",
    remaining_seconds,
    " sec"
  )
}


write_log <- function(
    ...,
    log_file,
    echo = TRUE
) {

  text <- paste0(...)

  line <- paste0(
    timestamp(),
    " | ",
    text
  )

  cat(
    line,
    "\n",
    file = log_file,
    append = TRUE,
    sep = ""
  )

  if (echo) {
    cat(
      line,
      "\n",
      sep = ""
    )
  }

  invisible(line)
}


separator_line <- function(
    character = "=",
    width = 78
) {

  paste(
    rep(
      character,
      width
    ),
    collapse = ""
  )
}


extract_stage_number <- function(script_name) {

  value <- stringr::str_extract(
    basename(script_name),
    "^[0-9]{2}"
  )

  suppressWarnings(
    as.integer(value)
  )
}


safe_file_exists <- function(path) {

  !is.na(path) &&
    nzchar(path) &&
    file.exists(path)
}


find_script <- function(
    project_dir,
    candidates
) {

  # Values stored in a tibble list-column may arrive here as a nested list.
  # Convert them to a simple character vector before using file/path helpers.
  candidates <- unlist(
    candidates,
    recursive = TRUE,
    use.names = FALSE
  )

  candidates <- as.character(
    candidates
  )

  candidates <- candidates[
    !is.na(candidates) &
      nzchar(candidates)
  ]

  if (length(candidates) == 0) {
    return(NA_character_)
  }

  exact_paths <- file.path(
    project_dir,
    candidates
  )

  exact_match <- exact_paths[
    file.exists(exact_paths)
  ]

  if (length(exact_match) > 0) {
    return(
      normalizePath(
        exact_match[1],
        winslash = "/",
        mustWork = TRUE
      )
    )
  }

  candidate_stems <- tools::file_path_sans_ext(
    basename(candidates)
  )

  all_r_scripts <- list.files(
    project_dir,
    pattern = "\\.R$",
    full.names = TRUE,
    recursive = FALSE
  )

  all_stems <- tools::file_path_sans_ext(
    basename(all_r_scripts)
  )

  matched <- all_r_scripts[
    all_stems %in%
      candidate_stems
  ]

  if (length(matched) > 0) {
    return(
      normalizePath(
        matched[1],
        winslash = "/",
        mustWork = TRUE
      )
    )
  }

  NA_character_
}


check_stage_outputs <- function(
    project_dir,
    output_paths
) {

  # expected_outputs is also stored as a list-column.
  output_paths <- unlist(
    output_paths,
    recursive = TRUE,
    use.names = FALSE
  )

  output_paths <- as.character(
    output_paths
  )

  output_paths <- output_paths[
    !is.na(output_paths) &
      nzchar(output_paths)
  ]

  if (length(output_paths) == 0) {
    return(NA)
  }

  full_paths <- file.path(
    project_dir,
    output_paths
  )

  all(
    file.exists(
      full_paths
    )
  )
}


run_script_in_clean_environment <- function(
    script_path,
    project_dir,
    show_output = TRUE,
    warnings_are_errors = FALSE
) {

  script_environment <- new.env(
    parent = globalenv()
  )

  warnings <- character(0)

  output <- character(0)

  stage_error <- NULL

  execution_expression <- quote(
    sys.source(
      script_path,
      envir = script_environment,
      chdir = TRUE
    )
  )

  handler <- function() {

    withCallingHandlers(
      eval(
        execution_expression,
        envir = environment()
      ),
      warning = function(warning_condition) {

        warnings <<- c(
          warnings,
          conditionMessage(
            warning_condition
          )
        )

        if (warnings_are_errors) {

          stop(
            conditionMessage(
              warning_condition
            )
          )

        } else {

          invokeRestart(
            "muffleWarning"
          )
        }
      }
    )
  }

  tryCatch(
    {

      output <- capture.output(
        handler(),
        type = "output"
      )
    },
    error = function(error_condition) {

      stage_error <<-
        conditionMessage(
          error_condition
        )
    }
  )

  if (
    show_output &&
    length(output) > 0
  ) {

    cat(
      paste(
        output,
        collapse = "\n"
      ),
      "\n"
    )
  }

  list(
    success = is.null(stage_error),
    error = stage_error,
    warnings = unique(warnings),
    output = output
  )
}


# =============================================================================
# 3. Required packages for Stage 18
# =============================================================================

stage18_packages <- c(
  "dplyr",
  "readr",
  "tibble",
  "stringr"
)

missing_stage18_packages <- setdiff(
  stage18_packages,
  rownames(
    installed.packages()
  )
)

if (
  length(
    missing_stage18_packages
  ) > 0
) {

  install.packages(
    missing_stage18_packages,
    dependencies = TRUE
  )
}

invisible(
  lapply(
    stage18_packages,
    library,
    character.only = TRUE
  )
)


# =============================================================================
# 4. Project paths
# =============================================================================

project_dir <- find_project_root()

outputs_dir <- file.path(
  project_dir,
  "outputs"
)

logs_dir <- file.path(
  outputs_dir,
  "logs"
)

create_directory(outputs_dir)
create_directory(logs_dir)

log_file <- file.path(
  logs_dir,
  "18_complete_pipeline.log"
)

summary_csv <- file.path(
  logs_dir,
  "18_pipeline_execution_summary.csv"
)

summary_rds <- file.path(
  logs_dir,
  "18_pipeline_execution_summary.rds"
)

session_file <- file.path(
  logs_dir,
  "18_sessionInfo.txt"
)

if (
  overwrite_log &&
  file.exists(log_file)
) {
  file.remove(log_file)
}


# =============================================================================
# 5. Pipeline stage registry
# =============================================================================
#
# Update candidate filenames here if your local filenames differ.
# The first existing candidate is used.
#
# required:
#   TRUE  = pipeline stops if script is unavailable or fails
#   FALSE = stage is reported as skipped if unavailable
#
# expected_outputs:
#   Used for status reporting only. Because force_rerun is TRUE by default,
#   the stages are still executed even if outputs already exist.
# =============================================================================

pipeline_registry <- tibble::tribble(
  ~stage, ~stage_name, ~required, ~script_candidates, ~expected_outputs,

  1L,
  "Load and audit",
  TRUE,
  list(
    c(
      "01_load_and_audit.R"
    )
  ),
  list(
    c(
      "data/processed/survey_audited.rds"
    )
  ),

  2L,
  "Data preprocessing",
  TRUE,
  list(
    c(
      "02_data_preprocessing.R"
    )
  ),
  list(
    c(
      "data/processed/segmentation_data_full.rds"
    )
  ),

  3L,
  "Data dictionary",
  TRUE,
  list(
    c(
      "03_data_dictionary.R"
    )
  ),
  list(
    c(
      "outputs/tables/03_data_dictionary.csv"
    )
  ),

  4L,
  "Exploratory segmentation check",
  TRUE,
  list(
    c(
      "04_exploratory_segmentation_check.R"
    )
  ),
  list(
    c(
      "outputs/tables/04_exploratory_summary.csv"
    )
  ),

  5L,
  "Feature quality assessment",
  TRUE,
  list(
    c(
      "05_feature_quality.R"
    )
  ),
  list(
    c(
      "data/processed/segmentation_selected_imputed.rds"
    )
  ),

  6L,
  "Corrected feature selection",
  TRUE,
  list(
    c(
      "06_feature_selection_corrected.R"
    )
  ),
  list(
    c(
      "data/processed/06_candidate_feature_sets.rds"
    )
  ),

  7L,
  "Distance comparison",
  TRUE,
  list(
    c(
      "07_distance_comparison.R"
    )
  ),
  list(
    c(
      "outputs/tables/07_distance_comparison_summary.csv"
    )
  ),

  8L,
  "Model comparison",
  TRUE,
  list(
    c(
      "08_model_comparison.R"
    )
  ),
  list(
    c(
      "outputs/tables/08_ranked_model_candidates.csv"
    )
  ),

  9L,
  "Model validation",
  TRUE,
  list(
    c(
      "09_model_validation.R"
    )
  ),
  list(
    c(
      "outputs/tables/09_validated_model_candidates.csv"
    )
  ),

  10L,
  "Final model selection",
  TRUE,
  list(
    c(
      "10_final_model_selection.R"
    )
  ),
  list(
    c(
      "outputs/tables/10_candidate_profile_summary.csv"
    )
  ),

  11L,
  "Final segment profiles",
  TRUE,
  list(
    c(
      "11_final_segment_profiles.R"
    )
  ),
  list(
    c(
      "outputs/tables/11_segment_sizes.csv",
      "outputs/tables/11_segment_distinguishing_variables.csv"
    )
  ),

  12L,
  "Segment naming and narratives",
  TRUE,
  list(
    c(
      "12_segment_naming_and_narratives.R"
    )
  ),
  list(
    c(
      "outputs/tables/12_segment_names.csv"
    )
  ),

  13L,
  "Final segment tables",
  TRUE,
  list(
    c(
      "13_final_segment_tables.R"
    )
  ),
  list(
    c(
      "outputs/final/13_segment_summary.xlsx"
    )
  ),

  14L,
  "Persona generation",
  TRUE,
  list(
    c(
      "14_persona_generation.R"
    )
  ),
  list(
    c(
      "outputs/final/14_persona_details.csv",
      "outputs/final/14_persona_cards.pdf"
    )
  ),

  15L,
  "Intervention recommendations",
  TRUE,
  list(
    c(
      "15_intervention_recommendations.R"
    )
  ),
  list(
    c(
      "outputs/final/15_intervention_recommendations.xlsx"
    )
  ),

  16L,
  "Report generation",
  TRUE,
  list(
    c(
      "16_report_generator.R"
    )
  ),
  list(
    c(
      "outputs/report/16_behavioural_segmentation_report.html",
      "outputs/report/16_behavioural_segmentation_report.docx"
    )
  ),

  17L,
  "Presentation generation",
  TRUE,
  list(
    c(
      "17_presentation_generator.R"
    )
  ),
  list(
    c(
      "outputs/presentation/17_behavioural_segmentation_presentation.pptx"
    )
  )
)


# =============================================================================
# 6. Apply requested stage range
# =============================================================================

if (
  !is.null(resume_from_stage)
) {

  if (
    !is.numeric(resume_from_stage) ||
    length(resume_from_stage) != 1 ||
    is.na(resume_from_stage)
  ) {
    stop(
      "resume_from_stage must be NULL or a single numeric stage number."
    )
  }

  pipeline_registry <- pipeline_registry |>
    dplyr::filter(
      stage >=
        as.integer(
          resume_from_stage
        )
    )
}

if (
  !is.null(stop_after_stage)
) {

  if (
    !is.numeric(stop_after_stage) ||
    length(stop_after_stage) != 1 ||
    is.na(stop_after_stage)
  ) {
    stop(
      "stop_after_stage must be NULL or a single numeric stage number."
    )
  }

  pipeline_registry <- pipeline_registry |>
    dplyr::filter(
      stage <=
        as.integer(
          stop_after_stage
        )
    )
}

if (
  nrow(pipeline_registry) == 0
) {
  stop(
    "No stages remain after applying resume_from_stage and stop_after_stage."
  )
}


# =============================================================================
# 7. Resolve script paths
# =============================================================================

pipeline_registry <- pipeline_registry |>
  dplyr::rowwise() |>
  dplyr::mutate(
    script_path = find_script(
      project_dir = project_dir,
      candidates = script_candidates
    ),
    script_exists = safe_file_exists(
      script_path
    ),
    outputs_exist_before =
      check_stage_outputs(
        project_dir,
        expected_outputs
      )
  ) |>
  dplyr::ungroup()


missing_required_scripts <- pipeline_registry |>
  dplyr::filter(
    required,
    !script_exists
  )

if (
  nrow(
    missing_required_scripts
  ) > 0
) {

  missing_message <- paste0(
    "Stage ",
    missing_required_scripts$stage,
    " — ",
    missing_required_scripts$stage_name,
    ": expected one of [",
    vapply(
      missing_required_scripts$script_candidates,
      paste,
      character(1),
      collapse = ", "
    ),
    "]",
    collapse = "\n"
  )

  stop(
    "Required pipeline scripts are missing:\n",
    missing_message,
    "\n\nUpdate pipeline_registry in 18_run_complete_pipeline.R ",
    "if your local filenames differ."
  )
}


# =============================================================================
# 8. Initialise execution
# =============================================================================

pipeline_start <- Sys.time()

write_log(
  separator_line(),
  log_file = log_file
)

write_log(
  "BEHAVIOURAL SEGMENTATION TOOLKIT — COMPLETE PIPELINE STARTED",
  log_file = log_file
)

write_log(
  separator_line(),
  log_file = log_file
)

write_log(
  "Project directory: ",
  project_dir,
  log_file = log_file
)

write_log(
  "Stages selected: ",
  min(pipeline_registry$stage),
  "–",
  max(pipeline_registry$stage),
  log_file = log_file
)

write_log(
  "Continue on error: ",
  continue_on_error,
  log_file = log_file
)

write_log(
  "Force rerun: ",
  force_rerun,
  log_file = log_file
)

write_log(
  separator_line("-"),
  log_file = log_file
)


execution_results <- vector(
  mode = "list",
  length = nrow(
    pipeline_registry
  )
)

pipeline_failed <- FALSE


# =============================================================================
# 9. Execute stages
# =============================================================================

for (
  row_index in
  seq_len(
    nrow(
      pipeline_registry
    )
  )
) {

  stage_row <- pipeline_registry[
    row_index,
    ,
    drop = FALSE
  ]

  stage_number <- stage_row$stage
  stage_name <- stage_row$stage_name
  script_path <- stage_row$script_path
  stage_required <- stage_row$required
  outputs_before <- stage_row$outputs_exist_before

  write_log(
    separator_line("-"),
    log_file = log_file
  )

  write_log(
    "STAGE ",
    sprintf(
      "%02d",
      stage_number
    ),
    " STARTED — ",
    stage_name,
    log_file = log_file
  )

  if (
    !stage_row$script_exists
  ) {

    write_log(
      "Stage skipped because the script is unavailable.",
      log_file = log_file
    )

    execution_results[[row_index]] <- tibble::tibble(
      stage = stage_number,
      stage_name = stage_name,
      script = NA_character_,
      required = stage_required,
      status = "SKIPPED_MISSING_SCRIPT",
      start_time = timestamp(),
      end_time = timestamp(),
      duration_seconds = 0,
      duration_formatted = "0 sec",
      outputs_existed_before = outputs_before,
      outputs_exist_after = outputs_before,
      warning_count = 0L,
      warnings = NA_character_,
      error = NA_character_
    )

    if (
      stage_required &&
      !continue_on_error
    ) {

      pipeline_failed <- TRUE
      break
    }

    next
  }

  if (
    !force_rerun &&
    isTRUE(
      outputs_before
    )
  ) {

    write_log(
      "Stage skipped because all expected outputs already exist.",
      log_file = log_file
    )

    execution_results[[row_index]] <- tibble::tibble(
      stage = stage_number,
      stage_name = stage_name,
      script = basename(
        script_path
      ),
      required = stage_required,
      status = "SKIPPED_OUTPUTS_EXIST",
      start_time = timestamp(),
      end_time = timestamp(),
      duration_seconds = 0,
      duration_formatted = "0 sec",
      outputs_existed_before = outputs_before,
      outputs_exist_after = outputs_before,
      warning_count = 0L,
      warnings = NA_character_,
      error = NA_character_
    )

    next
  }

  stage_start <- Sys.time()

  write_log(
    "Script: ",
    basename(
      script_path
    ),
    log_file = log_file
  )

  old_working_directory <- getwd()

  setwd(
    project_dir
  )

  stage_result <- run_script_in_clean_environment(
    script_path = script_path,
    project_dir = project_dir,
    show_output = show_stage_output,
    warnings_are_errors = warnings_are_errors
  )

  setwd(
    old_working_directory
  )

  stage_end <- Sys.time()

  stage_duration <- as.numeric(
    difftime(
      stage_end,
      stage_start,
      units = "secs"
    )
  )

  outputs_after <- check_stage_outputs(
    project_dir,
    stage_row$expected_outputs
  )

  if (
    stage_result$success
  ) {

    stage_status <- "SUCCESS"

    write_log(
      "STAGE ",
      sprintf(
        "%02d",
        stage_number
      ),
      " COMPLETED SUCCESSFULLY in ",
      format_duration(
        stage_duration
      ),
      log_file = log_file
    )

    if (
      length(
        stage_result$warnings
      ) > 0
    ) {

      write_log(
        "Warnings: ",
        paste(
          stage_result$warnings,
          collapse = " | "
        ),
        log_file = log_file
      )
    }

  } else {

    stage_status <- "FAILED"
    pipeline_failed <- TRUE

    write_log(
      "STAGE ",
      sprintf(
        "%02d",
        stage_number
      ),
      " FAILED after ",
      format_duration(
        stage_duration
      ),
      log_file = log_file
    )

    write_log(
      "Error: ",
      stage_result$error,
      log_file = log_file
    )
  }

  execution_results[[row_index]] <- tibble::tibble(
    stage = stage_number,
    stage_name = stage_name,
    script = basename(
      script_path
    ),
    required = stage_required,
    status = stage_status,
    start_time = format(
      stage_start,
      "%Y-%m-%d %H:%M:%S"
    ),
    end_time = format(
      stage_end,
      "%Y-%m-%d %H:%M:%S"
    ),
    duration_seconds = stage_duration,
    duration_formatted =
      format_duration(
        stage_duration
      ),
    outputs_existed_before = outputs_before,
    outputs_exist_after = outputs_after,
    warning_count = length(
      stage_result$warnings
    ),
    warnings = ifelse(
      length(
        stage_result$warnings
      ) == 0,
      NA_character_,
      paste(
        stage_result$warnings,
        collapse = " | "
      )
    ),
    error = ifelse(
      is.null(
        stage_result$error
      ),
      NA_character_,
      stage_result$error
    )
  )

  if (
    !stage_result$success &&
    stage_required &&
    !continue_on_error
  ) {

    write_log(
      "Pipeline stopped because a required stage failed.",
      log_file = log_file
    )

    break
  }
}


# =============================================================================
# 10. Consolidate execution results
# =============================================================================

execution_results <- execution_results[
  !vapply(
    execution_results,
    is.null,
    logical(1)
  )
]

if (
  length(
    execution_results
  ) > 0
) {

  execution_summary <- dplyr::bind_rows(
    execution_results
  )

} else {

  execution_summary <- tibble::tibble(
    stage = integer(),
    stage_name = character(),
    script = character(),
    required = logical(),
    status = character(),
    start_time = character(),
    end_time = character(),
    duration_seconds = numeric(),
    duration_formatted = character(),
    outputs_existed_before = logical(),
    outputs_exist_after = logical(),
    warning_count = integer(),
    warnings = character(),
    error = character()
  )
}

readr::write_csv(
  execution_summary,
  summary_csv,
  na = ""
)

saveRDS(
  execution_summary,
  summary_rds
)


# =============================================================================
# 11. Save reproducibility information
# =============================================================================

capture.output(
  sessionInfo(),
  file = session_file
)


# =============================================================================
# 12. Final pipeline status
# =============================================================================

pipeline_end <- Sys.time()

pipeline_duration <- as.numeric(
  difftime(
    pipeline_end,
    pipeline_start,
    units = "secs"
  )
)

successful_stages <- sum(
  execution_summary$status ==
    "SUCCESS",
  na.rm = TRUE
)

failed_stages <- sum(
  execution_summary$status ==
    "FAILED",
  na.rm = TRUE
)

skipped_stages <- sum(
  stringr::str_starts(
    execution_summary$status,
    "SKIPPED"
  ),
  na.rm = TRUE
)

pipeline_status <- if (
  failed_stages == 0 &&
  !pipeline_failed
) {
  "SUCCESS"
} else {
  "FAILED"
}


write_log(
  separator_line(),
  log_file = log_file
)

write_log(
  "BEHAVIOURAL SEGMENTATION TOOLKIT — COMPLETE PIPELINE FINISHED",
  log_file = log_file
)

write_log(
  separator_line(),
  log_file = log_file
)

write_log(
  "Pipeline status: ",
  pipeline_status,
  log_file = log_file
)

write_log(
  "Successful stages: ",
  successful_stages,
  log_file = log_file
)

write_log(
  "Failed stages: ",
  failed_stages,
  log_file = log_file
)

write_log(
  "Skipped stages: ",
  skipped_stages,
  log_file = log_file
)

write_log(
  "Total execution time: ",
  format_duration(
    pipeline_duration
  ),
  log_file = log_file
)

write_log(
  "Execution summary: ",
  summary_csv,
  log_file = log_file
)

write_log(
  "Pipeline log: ",
  log_file,
  log_file = log_file
)

write_log(
  separator_line(),
  log_file = log_file
)


# =============================================================================
# 13. Console summary
# =============================================================================

cat(
  "\n",
  separator_line(),
  "\n",
  "BEHAVIOURAL SEGMENTATION TOOLKIT — COMPLETE PIPELINE ",
  pipeline_status,
  "\n",
  separator_line(),
  "\n",
  "Stages selected:                ",
  min(
    pipeline_registry$stage
  ),
  "–",
  max(
    pipeline_registry$stage
  ),
  "\n",
  "Stages completed successfully:  ",
  successful_stages,
  "\n",
  "Stages failed:                  ",
  failed_stages,
  "\n",
  "Stages skipped:                 ",
  skipped_stages,
  "\n",
  "Total execution time:           ",
  format_duration(
    pipeline_duration
  ),
  "\n",
  "Execution summary:\n",
  summary_csv,
  "\n",
  "Pipeline log:\n",
  log_file,
  "\n",
  separator_line(),
  "\n",
  sep = ""
)


# =============================================================================
# 14. Raise final error when pipeline failed
# =============================================================================

if (
  pipeline_status != "SUCCESS"
) {

  failed_details <- execution_summary |>
    dplyr::filter(
      status == "FAILED"
    ) |>
    dplyr::transmute(
      detail = paste0(
        "Stage ",
        sprintf(
          "%02d",
          stage
        ),
        " — ",
        stage_name,
        ": ",
        error
      )
    ) |>
    dplyr::pull(
      detail
    )

  stop(
    "Complete pipeline did not finish successfully.\n",
    paste(
      failed_details,
      collapse = "\n"
    ),
    "\nSee the log file for details:\n",
    log_file,
    call. = FALSE
  )
}
